const nicknames = [
  {
    name: 'Abraham Ancer',
    replace: 'Honest Abe',
    middle: 'Abraham "Honest Abe" Ancer',
    after: 'Abraham Ancer (Honest Abe)',
  },
  {
    name: 'Cameron Champ',
    replace: "Don't Call me Cam",
    middle: 'Cameron "Don\'t Call me Cam" Champ',
    after: "Cameron Champ (Don't Call me Cam)",
  },
  {
    name: 'K.J. Choi',
    replace: 'Choi Boi',
    middle: 'K.J. "Choi Boi" Choi',
    after: 'K.J. Choi (Choi Boi)',
  },
  {
    name: 'Joel Dahmen',
    replace: 'Joely D',
    middle: 'Joel "Joely D" Dahmen',
    after: 'Joel Dahmen (Joely D)',
  },
  {
    name: 'Jason Day',
    replace: 'Balloon Boy',
    middle: 'Jason "Balloon Boy" Day',
    after: 'Jason Day (Balloon Boy)',
  },
  {
    name: 'Ernie Els',
    replace: 'Big Ern',
    middle: 'Ernie "Big Ern" Els',
    after: 'Ernie Els (Big Ern)',
  },
  {
    name: 'Rickie Fowler',
    replace: 'Slick Rick',
    middle: 'Rickie "Slick Rick" Fowler',
    after: 'Rickie Fowler (Slick Rick)',
  },
  {
    name: 'Tommy Gainey',
    replace: 'Solicitor General',
    middle: 'Tommy "Solicitor General" Gainey',
    after: 'Tommy Gainey (Solicitor General)',
  },
  {
    name: 'Sergio Garcia',
    replace: 'Big Tex',
    middle: 'Sergio "Big Tex" Garcia',
    after: 'Sergio Garcia (Big Tex)',
  },
  {
    name: 'J.J. Henry',
    replace: 'Mr. 300',
    middle: 'J.J. "Mr. 300" Henry',
    after: 'J.J. Henry (Mr. 300)',
  },
  {
    name: 'Tom Hoge',
    replace: 'Tommy Tables',
    middle: 'Tom "Tommy Tables" Hoge',
    after: 'Tom Hoge (Tommy Tables)',
  },
  {
    name: 'J.B. Holmes',
    replace: 'The Pace Car',
    middle: 'J.B. "The Pace Car" Holmes',
    after: 'J.B. Holmes (The Pace Car)',
  },
  {
    name: 'Zach Johnson',
    replace: 'Zatch',
    middle: 'Zach "Zatch" Johnson',
    after: 'Zach Johnson (Zatch)',
  },
  {
    name: 'Si Woo Kim',
    replace: 'Big Woo Woo',
    middle: 'Si Woo "Big Woo Woo" Kim',
    after: 'Si Woo Kim (Big Woo Woo)',
  },
  {
    name: 'Jim Knous',
    replace: 'Jimmy Hard K',
    middle: 'Jim "Jimmy Hard K" Knous',
    after: 'Jim Knous (Jimmy Hard K)',
  },
  {
    name: 'K.H. Lee',
    replace: 'Husky Boy',
    middle: 'K.H. "Husky Boy" Lee',
    after: 'K.H. Lee (Husky Boy)',
  },
  {
    name: 'Tom Lehman',
    replace: 'Tommy Dockers',
    middle: 'Tom "Tommy Dockers" Lehman',
    after: 'Tom Lehman (Tommy Dockers)',
  },
  {
    name: 'Adam Long',
    replace: 'Sidecar',
    middle: 'Adam "Sidecar" Long',
    after: 'Adam Long (Sidecar)',
  },
  {
    name: 'Dru Love',
    replace: 'Little Boy Dru',
    middle: 'Dru "Little Boy Dru" Love',
    after: 'Dru Love (Little Boy Dru)',
  },
  {
    name: 'Billy Mayfair',
    replace: 'Billy Playfair',
    middle: 'Billy "Billy Playfair" Mayfair',
    after: 'Billy Mayfair (Billy Playfair)',
  },
  {
    name: 'Scott McCarron',
    replace: 'Anchorman',
    middle: 'Scott "Anchorman" McCarron',
    after: 'Scott McCarron (Anchorman)',
  },
  {
    name: 'Rory McIlroy',
    replace: 'The Prince of Ponte Vedra',
    middle: 'Rory "The Prince of Ponte Vedra" McIlroy',
    after: 'Rory McIlroy (The Prince of Ponte Vedra)',
  },
  {
    name: 'Phil Mickelson',
    replace: 'Saudi Boi',
    middle: 'Phil "Saudi Boi" Mickelson',
    after: 'Phil Mickelson (Saudi Boi)',
  },
  {
    name: 'Jay Monahan',
    replace: 'Big Jay',
    middle: 'Jay "Big Jay" Monahan',
    after: 'Jay Monahan (Big Jay)',
  },
  {
    name: 'Louis Oosthuizen',
    replace: 'The Mattress King',
    middle: 'Louis "The Mattress King" Oosthuizen',
    after: 'Louis Oosthuizen (The Mattress King)',
  },
  {
    name: 'Carl Petersson',
    replace: 'The Swedish Pancake',
    middle: 'Carl "The Swedish Pancake" Petersson',
    after: 'Carl Petersson (The Swedish Pancake)',
  },
  {
    name: 'Chez Reavie',
    replace: 'Big Bill',
    middle: 'Chez "Big Bill" Reavie',
    after: 'Chez Reavie (Big Bill)',
  },
  {
    name: 'Rory Sabbatini',
    replace: 'The Boy From Bratislava',
    middle: 'Rory "The Boy From Bratislava" Sabbatini',
    after: 'Rory Sabbatini (The Boy From Bratislava)',
  },
  {
    name: 'Charl Schwartzel',
    replace: 'Hot Charl',
    middle: 'Charl "Hot Charl" Schwartzel',
    after: 'Charl Schwartzel (Hot Charl)',
  },
  {
    name: 'Kevin Streelman',
    replace: 'Sunday Streels',
    middle: 'Kevin "Sunday Streels" Streelman',
    after: 'Kevin Streelman (Sunday Streels)',
  },
  {
    name: 'Kevin Tway',
    replace: 'Gainz',
    middle: 'Kevin "Gainz" Tway',
    after: 'Kevin Tway (Gainz)',
  },
  {
    name: 'Jimmy Walker',
    replace: 'Texas Backstopper',
    middle: 'Jimmy "Texas Backstopper" Walker',
    after: 'Jimmy Walker (Texas Backstopper)',
  },
  {
    name: 'Mike Weir',
    replace: 'The Wounded Duck',
    middle: 'Mike "The Wounded Duck" Weir',
    after: 'Mike Weir (The Wounded Duck)',
  },
  {
    name: 'Lee Westwood',
    replace: 'Westy',
    middle: 'Lee "Westy" Westwood',
    after: 'Lee Westwood (Westy)',
  },
  {
    name: 'Bernd Wiesberger',
    replace: 'Burnt Cheeseburger',
    middle: 'Bernd "Burnt Cheeseburger" Wiesberger',
    after: 'Bernd Wiesberger (Burnt Cheeseburger)',
  },
]

export default nicknames
